import React from 'react';

const Card = ({ title, description, icon, color }) => (
  <article 
    tabIndex="0"
    className="relative group rounded-2xl bg-slate-800/50 border border-slate-700/50 p-6 backdrop-blur-sm overflow-hidden transition-all duration-300 hover:bg-slate-800/80 hover:-translate-y-1 hover:shadow-xl hover:shadow-brand-500/10 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2 focus:ring-offset-slate-900"
  >
    <div className={`absolute top-0 right-0 w-32 h-32 bg-gradient-to-br ${color} opacity-10 rounded-full blur-2xl group-hover:opacity-20 transition-opacity`}></div>
    <div 
      className="w-12 h-12 rounded-xl bg-slate-800 border border-slate-700 flex items-center justify-center text-2xl mb-4 group-hover:scale-110 transition-transform"
      role="img"
      aria-label={title}
    >
      {icon}
    </div>
    <h3 className="text-xl font-semibold text-slate-100 mb-2">{title}</h3>
    <p className="text-slate-400 text-sm leading-relaxed">
      {description}
    </p>
  </article>
);

export default function Dashboard() {
  return (
    <div className="space-y-12">
      <div className="text-center max-w-3xl mx-auto space-y-4">
        <h2 className="text-4xl md:text-5xl font-extrabold tracking-tight">
          Understand your <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-400 to-emerald-400">Impact</span>
        </h2>
        <p className="text-lg text-slate-400">
          A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card 
          title="Transportation" 
          description="Driving a car or taking public transit burns fossil fuels. Personal vehicles are a major contributor to global emissions."
          icon="🚗"
          color="from-blue-400 to-indigo-500"
        />
        <Card 
          title="Energy Usage" 
          description="Electricity for our homes often comes from coal or natural gas plants. Optimizing usage reduces your footprint."
          icon="⚡"
          color="from-yellow-400 to-orange-500"
        />
        <Card 
          title="Diet & Food" 
          description="The food we eat, especially meat, requires significant energy and land to produce, generating substantial methane."
          icon="🥗"
          color="from-emerald-400 to-green-500"
        />
      </div>
    </div>
  );
}
